source 'https://rubygem.org'
gem 'bundler'

# points to a release
gem 'rack', '~>1.5.2'
# User a specific version
gem 'sinatra', '1.4.1'
# use at least a version ro anything greater
gem 'uglifier',  '>= 1.3.0'

# pull gem from git repo
gem 'sinatra', git: 'https://github.com/sinatra/sinatra.git'
# you can specify a sha
gem 'sinatra', git: 'https://github.com/sinatra/sinatra.git', sha: '30d4fb468fd1d6373f82127d845b153f17b54c51'
# you can also specify a branch, though this is often unsafe
gem 'sinatra', git: 'https://github.com/sinatra/sinatra.git', branch: 'master'

# you can group gem depending on what they are used for
group :development, :test do
    # This gem is only available in dev and test, not production. 
    gem 'byebug'
end