#!/usr/bin/ruby

require 'open3'

p "please enter commit message"
stdin_data = gets

commands = ['git add .', \
            'git commit -m "' + stdin_data +'"', \
            'git push']

for command in commands
    stdin, stdout, stderr, wait_thr = Open3.popen3(command)
    puts "stdout is:" + stdout.read
    puts "stderr is:" + stderr.read
#    system (command)
#    p command
end


