services:
  tutorial:
    image: python:3.9-slim
    container_name: tutorial
    working_dir: /app  # Set the container's working directory
    ports:
      - "8888:8888"
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y --no-install-recommends build-essential gcc git &&
      pip install pretzelai &&
      pip install torch torchvision torchaudio &&
      jupyter lab --ip=0.0.0.0 --allow-root --notebook-dir=/app --ServerApp.token='' --no-browser
      "
