version: '3.9'

services:
  pretzel:
    image: python:3.9-slim
    container_name: pretzel-lab
    working_dir: /app  # Set the container's working directory
    ports:
      - "8888:8888"
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y --no-install-recommends build-essential gcc &&
      pip install pretzelai &&
      pretzel lab --ip=0.0.0.0 --allow-root --notebook-dir=/app --ServerApp.allow_remote_access=True --ServerApp.token='' --no-browser
      "