# need to install
# # Reconfigure NVIDIA Container Runtime
# sudo nvidia-ctk runtime configure --runtime=docker

# # Make sure the runtime is set as default
# sudo nvidia-ctk runtime configure --runtime=docker --set-as-default

# # Restart Docker daemon
# sudo systemctl restart docker
services:
  tutorial:
    image: nvidia/cuda:12.6.3-base-ubuntu20.04
    container_name: tutorial-gpu
    working_dir: /app
    extra_hosts:
      - "localhost:192.168.65.2"
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [compute, utility]
              count: all
    command: >
      sh -c "
      apt-get update && \
      apt-get install -y --no-install-recommends build-essential gcc git python3 python3-pip python3-dev rustc cargo && \
      python3 -m pip install --upgrade pip setuptools wheel && \
      python3 -m pip install 'onnxruntime>=1.17.0,<1.20.0' && \
      python3 -m pip install pretzelai && \
      python3 -m pip install torch torchvision torchaudio && \
      python3 -m pip install tokenizers==0.20.3 && \
      jupyter lab --ip=0.0.0.0 --allow-root --notebook-dir=/app --ServerApp.token='' --no-browser
      "

