#! /bin/bash

pinghost ()
{
    echo which host you wnat to ping?
    read HOSTNAME
    ping -c -1 $HOSTNAME
}

while true;
do
    # user cannot ctrl out ofthe script
    trap "echo NOPE" INT
    
    echo'select an option?'
    select TASK in 'Reset password' 'Show disk usage' 'Ping a host' 'Log out'
    do
        case $REPLY in
            1) TASK=passwd;;
            2) TASK="df -h";;
            3) TASK=pinghost;;
            4) TASK=exit;;
            *) echo ERROR && exit 2;;
        esac
        if [ -n "$TASK" ]
        then
            clear
            $TASK
            break
        else
            echo INVALID CHOICE && exit 3
        fi
    done
done