version: "3"

services:

  fleetman-webapp:
    image: virtualpairprogrammers/fleetman-production
    networks:
      - fleetman-network
    ports:
      - 80:8000
    depends_on:
      - database

  database:
    image: mysql:8.0.16
    networks:
      - fleetman-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fleetman

networks:
  fleetman-network:
