node {
    stage('Preparation') {
        git 'https://github.com/YilengYao/tutorials/tree/master/dockerjava/DockerTomcat'
    }
    stage('Build') {
        git "mvn -DskipTests clean package"
    }
    stage('Results') {
        archive 'target/*.war'
    }
    stage('Deploy') {
        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'awscredentials', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
            ansiblePlaybook credentialsId: 'ssh', installation: 'ansible', playbook: 'deploy.yaml', sudoUser: null
        }
    }
}