#! /bin/bash                                                                                                             
INTERVAL=$1                                                                                                              
# user set interval which cpu monitoring happens                               
while sleep $INTERVAL 
do    
        VALUE=$(ps -eo pcpu,pid -o comm= | sort -k1 -n -r | head -1)
        USAGE1=$(echo $VALUE | awk '{ print $1 }')
        USAGE1=${USAGE1%.*} 
        PID1=$(echo $VALUE | awk '{ print $2 }')                               
        PNAME1=$(echo $VALUE | awk '{ print $3 }')
        # the following code is to see if usage is greater than 80%
        if [ $USAGE1 -gt 80 ]       
        then  
                sleep 7 
                VALUE2=$(ps -eo pcpu,pid -o comm= | sort -k1 -n -r | head -1)
                USAGE2=$(echo $VALUE2 | awk '{ print $1 }')
                USAGE2=${USAGE2%.*}
                PID2=$(echo $VALUE2 | awk '{ print $2 }')
                PNAME2=$(echo $VALUE2 | awk '{ print $3 }')       
                [ $USAGE2 -gt 80 ] && [ $PID1 = $PID2 ] && \ 
                    mail -s "CPU load of $PNAME2 is above 80%" root < . 
        fi              
done